### ISSUE TITLE
Units are not counted towards their current work assignment while depositing resources

### ISSUE THREAD

**Issue by PROMETHIA-27** [SoLegendary/ageofcraft#31]
The tallies to the right of each resource counting workers assigned to gather that resource flicker while the workers are depositing; this makes it harder to tell exactly how many you actually have on that resource at a time.

**Comment by SoLegendary** [comment]
easy fix, thanks for noticing
EDIT: I had to jynx myself by saying that. Turns out I don't track whether a worker is returning to drop off on the clientside so i'll just consider holding a resource (and not idle) as counting to the total, this should cover most cases since workers are usually not holding resources while doing other stuff.

**Comment by SoLegendary** [comment]
The logic I'll implement is if they're holding any non-zero amount of a resource they'll add to the total, so one worker holding a bit of all 3 resources will count as 1 of each in the total assigned count. This might be a bit weird, but I don't reckon it will happen very often.
